### ISSUE TITLE
Error occurs in the module `@event-calendar/day-grid/src/Header.svelte` line 11

### ISSUE THREAD

**Issue by vkurko** [vkurko/calendar#179]
> > I would imagine something like this:
> > ```svelte
> > theme : {
> >   view : {
> >     dayGridMonth : 'ec-day-grid ec-month-view',
> >     listDay : 'ec-list ec-day-view',
> >     listMonth : 'ec-list ec-month-view',
> >     listWeek : 'ec-list ec-week-view',
> >     listYear : 'ec-list ec-year-view',
> >     resourceTimeGridDay : 'ec-time-grid ec-resource-day-view',
> >     resourceTimeGridWeek : 'ec-time-grid ec-resource-week-view',
> >     timeGridDay : 'ec-time-grid ec-day-view',
> >     timeGridWeek : 'ec-time-grid ec-week-view'
> >   }
> > }
> > ```
> 
> I like this idea. I wonder why I didn't think of this before 😄
> 

Great, implementing this would probably already fix my issues.

> > This leads me to believe that the error in version `2.3.0` has nothing to do with only a missing `weekdays` field but rather with some entirely corrupted store variable.
> 
> The `weekdays` field was added in v2.3.0. It seems that for version 2.3.0 you are passing the `theme` object from version 2.2.0, where this field did not exist yet.
> 
> I have not yet been able to reproduce the issue locally in SvelteKit.

@vkurko This error only occurs if I set a function (i.e. the one from my previous comment) to the `theme` variable and not when I set a static dictionary. So there is no way that I am passing the incorrect object. ;) The `weekdays` field does get properly set in the theme variable that is passed to the function and so does everything else (compared it to the default by console logging). From the debug output I can see that the error occurs in the module `@event-calendar/day-grid/src/Header.svelte` line 11, right here:

```svelte
import {
	SvelteComponentDev,
	action_destroyer,
	add_location,
	append_hydration_dev,
	attr_dev,
	children,
	claim_element,
	claim_space,
	component_subscribe, // <<= Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
	destroy_each,
	detach_dev,
	dispatch_dev,
	element,
	ensure_array_like_dev,
	init,
	insert_hydration_dev,
	is_function,
	noop,
	safe_not_equal,
	space,
	validate_slots,
	validate_store
} from "/node_modules/.vite/deps/svelte_internal.js?v=3021394d";

...

// The above error points to an issue somewhere here, however there does not seem to be any more debug info
function instance($$self, $$props, $$invalidate) {
	let $theme;
	let $_days;
	let $_intlDayHeader;
	let { $$slots: slots = {}, $$scope } = $$props;
	validate_slots('Header', slots, []);
	let { theme, _intlDayHeader, _days } = getContext('state');
	validate_store(theme, 'theme');

        // The error "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')" seems to point at this line
	component_subscribe($$self, theme, value => $$invalidate(0, $theme = value));
	validate_store(_intlDayHeader, '_intlDayHeader');
	component_subscribe($$self, _intlDayHeader, value => $$invalidate(2, $_intlDayHeader = value));
	validate_store(_days, '_days');
	component_subscribe($$self, _days, value => $$invalidate(1, $_days = value));
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== '$$' && key !== 'slot') console.warn(`<Header> was created with unknown prop '${key}'`);
	});

	$$self.$capture_state = () => ({
		getContext,
		setContent,
		theme,
		_intlDayHeader,
		_days,
		$theme,
		$_days,
		$_intlDayHeader
	});

	$$self.$inject_state = $$props => {
		if ('theme' in $$props) $$invalidate(3, theme = $$props.theme);
		if ('_intlDayHeader' in $$props) $$invalidate(4, _intlDayHeader = $$props._intlDayHeader);
		if ('_days' in $$props) $$invalidate(5, _days = $$props._days);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [$theme, $_days, $_intlDayHeader, theme, _intlDayHeader, _days];
}
```
```console
Header.svelte:11 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Object.hydrate [as h] (Header.svelte:11:46)
    at Object.create [as c] (stores.js:23:1)
    at Object.create [as c] (Header.svelte:10:15)
    at create_component (Component.js:33:17)
    at Object.create [as c] (View.svelte:29:7)
    at create_component (Component.js:33:17)
    at Object.create [as c] (Calendar.svelte:137:44)
    at create_component (Component.js:33:17)
    at Object.create [as c] (+page.svelte:126:34)
    at Object.create [as c] (Content.svelte:4:43)
```

Could it be that you are not properly unsubscribing from a store on destroying a component? I am just handwaving here, since I am not familiar with your code base but the issue is definitely related to stores, funnily enough only if `theme` is set to a function though.

_Originally posted by @LeonHeidelbach in https://github.com/vkurko/calendar/issues/155#issuecomment-1695431053_

**Comment by vkurko** [comment]
@LeonHeidelbach This issue should be fixed in v2.3.1. Please check.

**Comment by LeonHeidelbach** [comment]
@vkurko I can confirm that the error now no longer occurs. However, with the updated version the same issue as in `v.2.2.0` arises. On the initial page load everything renders correctly but after even a hotreload of the page when using `vite dev` the calendar classes all seem to dissapear. For some reason almost all fields that hold the calendar's class lists are now undefined. I am still using only this function to alter the theme:

```svelte
theme: (theme: CalendarThemeOptions) => {
	theme.button = `ec-button dark:!bg-gray-800 dark:!text-white dark:hover:!bg-gray-700
		            hover:cursor-pointer`;
	theme.icon = 'ec-icon dark:after:!border-white';
	theme.today = 'ec-today dark:!bg-gray-600 dark:!text-white';
	return theme;
},
```

As you can see on the screenshot below, weirdly enough a couple of classes seem to still be available.

![image](https://github.com/vkurko/calendar/assets/55194243/dda40b30-ca3e-4716-95ba-8bf6ac67e543)

**Comment by vkurko** [comment]
Oh that SvelteKit! :upside_down_face: I'll look into this.

**Comment by vkurko** [comment]
@LeonHeidelbach Ok, there is v2.3.2. Lots of changes in hopes of fixing the problem. Please check.

**Comment by LeonHeidelbach** [comment]
@vkurko Yes, this now finally does the trick. Thank you for your efforts! :+1:

**Comment by vkurko** [comment]
Great! 😄
