### ISSUE TITLE
Unexpected token (238:11)

### ISSUE THREAD

**Issue by oldmanwerther** [vkurko/calendar#218]
@event-calendar\core\index.js: Unexpected token (238:11) ... which is  return Math.max(...args);

Can't seem to get around this when importing and then compiling. Nodejs v20. Gulp 4.0. Using as an ES6 import.

**Comment by vkurko** [comment]
`...` is a **rest parameters** syntax which should be available in Node.js [since](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters#browser_compatibility) v6.0.0. Are you sure the error is from Node.js?

**Comment by oldmanwerther** [comment]
here's full output:

[09:34:22] 'scripts_global' errored after 1.86 s
[09:34:22] Error: Parsing file C:\Users\RobertGeiger\Documents\GitHub\WRA.Umbraco\src\WRA.Umbraco.Web\node_modules\@event-calendar\core\index.js: Unexpected token (238:11)
    at Deps.parseDeps (C:\Users\RobertGeiger\Documents\GitHub\WRA.Umbraco\src\WRA.Umbraco.Web\node_modules\module-deps\index.js:519:15)
    at getDeps (C:\Users\RobertGeiger\Documents\GitHub\WRA.Umbraco\src\WRA.Umbraco.Web\node_modules\module-deps\index.js:447:44)
    at C:\Users\RobertGeiger\Documents\GitHub\WRA.Umbraco\src\WRA.Umbraco.Web\node_modules\module-deps\index.js:430:38
    at ConcatStream.<anonymous> (C:\Users\RobertGeiger\Documents\GitHub\WRA.Umbraco\src\WRA.Umbraco.Web\node_modules\concat-stream\index.js:37:43)
    at ConcatStream.emit (node:events:530:35)
    at ConcatStream.emit (node:domain:551:15)
    at finishMaybe (C:\Users\RobertGeiger\Documents\GitHub\WRA.Umbraco\src\WRA.Umbraco.Web\node_modules\readable-stream\lib\_stream_writable.js:630:14)
    at endWritable (C:\Users\RobertGeiger\Documents\GitHub\WRA.Umbraco\src\WRA.Umbraco.Web\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at Writable.end (C:\Users\RobertGeiger\Documents\GitHub\WRA.Umbraco\src\WRA.Umbraco.Web\node_modules\readable-stream\lib\_stream_writable.js:594:22)
    at DuplexWrapper.onend (C:\Users\RobertGeiger\Documents\GitHub\WRA.Umbraco\src\WRA.Umbraco.Web\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:632:28)
    at DuplexWrapper.emit (node:events:530:35)
    at DuplexWrapper.emit (node:domain:551:15)
    at endReadableNT (C:\Users\RobertGeiger\Documents\GitHub\WRA.Umbraco\src\WRA.Umbraco.Web\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[09:34:22] 'scripts' errored after 1.86 s
[09:34:22] 'build' errored after 1.87 s

**Comment by vkurko** [comment]
Unfortunately, this does not add clarity. **Spread sytanx** is available in Node.js [since](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) v5.0.0, **Rest parameters** syntax since v6.0.0. Perhaps your build tool uses a different version of Node.js?

**Comment by vkurko** [comment]
@oldmanwerther any update?

**Comment by vkurko** [comment]
I hope I can close this issue.
