### ISSUE TITLE
Select callback through error

### ISSUE THREAD

**Issue by kawasaki656** [vkurko/calendar#357]
I am using @event-calendar/resource-time-grid and @event-calendar/interaction plugins together with resourceTimeGridWeek view. I performed a flag selectable: true.
I am trying to add an event by hitting calendar view but it through an error with the following trace

index.js:277 Uncaught TypeError: Cannot read properties of null (reading 'Symbol(ec)')
    at getPayload (index.js:277:1)
    at common (index.js:244:1)
    at HTMLDivElement.select (index.js:213:1)
    at HTMLDivElement.<anonymous> (index.js:1234:1)

The problem only exists on resource time grid, I've no this problem on @event-calendar/time-grid

dependencies:
"@event-calendar/core": "3.6.2",
"@event-calendar/interaction": "3.6.2",
"@event-calendar/resource-time-grid": "3.6.2",
"@event-calendar/time-grid": "3.6.2",

**Comment by vkurko** [comment]
Please see this [comment](https://github.com/vkurko/calendar/issues/349#issuecomment-2414057038).

**Comment by kawasaki656** [comment]
@vkurko thanks but I don't use height definition at all

**Comment by kawasaki656** [comment]
@vkurko maybe you have code of this demo https://vkurko.github.io/calendar/ where resource plugin works without issues ?

**Comment by vkurko** [comment]
Here is the [code](https://github.com/vkurko/calendar/blob/5b10cf3acb9b101cc20323adb4af1e0c54e60665/docs/index.html).

**Comment by kawasaki656** [comment]
@vkurko strange but this base functionality doesn't work even I create a project from scratch and doesn't perform any styles to calendar(use only default)
Can you check pls ?
`import React, { useEffect } from "react";
import Calendar from '@event-calendar/core';
import ResourceTimeGrid from '@event-calendar/resource-time-grid';
import '@event-calendar/core/index.css';
import Interaction from '@event-calendar/interaction';

let ResourceCalendar: any;

const ResourceScheduler = (props: any): JSX.Element => {
	useEffect(() => {
		if (!ResourceCalendar) {
			ResourceCalendar = new Calendar({
				// @ts-ignore
				target: document.getElementById('resource-scheduler'),
				props: {
					plugins: [ResourceTimeGrid, Interaction],
					options: {
						view: 'resourceTimeGridWeek',
						selectable: true,
						nowIndicator: true,
						resources: props.resources,
					}
				}
			});
		}
		return () => {
			ResourceCalendar = undefined;
		}
	}, [])
	return (
		<>
			<div id="resource-scheduler"></div>
		</>
	)
}

export default ResourceScheduler;
`
<img width="685" alt="Screenshot 2024-10-23 at 08 01 24" src="https://github.com/user-attachments/assets/970ebfdd-bc7e-4aee-94bf-fdd333148de6">
<img width="681" alt="Screenshot 2024-10-23 at 08 02 13" src="https://github.com/user-attachments/assets/e8d37a0a-cf0a-4834-8bf0-54fa050315c2">

**Comment by vkurko** [comment]
I prepared a [demo](https://stackblitz.com/edit/vitejs-vite-gfgp3p?file=src%2FApp.tsx) using your code and do not see the error. Can you reproduce it?

**Comment by vkurko** [comment]
@kawasaki656 Any update on this?
